In [1]:
import numpy as np

In [2]:
liste = [10,20,30]
vector = np.array(liste)
print(vector)

[10 20 30]


In [3]:
liste = [[5,10,15],[20,25,30],[35,40,45]]
matrix = np.array(liste)
print(matrix)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [4]:
print(vector.shape)
print(matrix.shape)

(3,)
(3, 3)


In [6]:
# fonction numpy pour lire un dataset
word_alcol = np.genfromtxt('world_alcohol.csv',delimiter=',')
print(word_alcol.shape)
print(type(word_alcol))

(3258, 5)
<class 'numpy.ndarray'>


In [7]:
world_alcol_dtype = word_alcol.dtype
print(world_alcol_dtype)

float64


In [8]:
word_alcol

array([[      nan,       nan,       nan,       nan,       nan],
       [1.986e+03,       nan,       nan,       nan, 0.000e+00],
       [1.986e+03,       nan,       nan,       nan, 5.000e-01],
       ...,
       [1.986e+03,       nan,       nan,       nan, 2.540e+00],
       [1.987e+03,       nan,       nan,       nan, 0.000e+00],
       [1.986e+03,       nan,       nan,       nan, 5.150e+00]])

In [75]:
word_alcohol = np.genfromtxt('world_alcohol.csv',delimiter=",",dtype="U75",skip_header=1)
word_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

In [14]:
ivoire_1985 = word_alcohol[2,4]
second_contry = word_alcohol[1,2]
print(ivoire_1985)
print(second_contry)


1.62
Uruguay


In [17]:
country = word_alcohol[:,2]
print(country)

['Viet Nam' 'Uruguay' "Cte d'Ivoire" ... 'Switzerland' 'Papua New Guinea'
 'Swaziland']


In [19]:
alcol_consomtion = word_alcohol[:,4]
print(alcol_consomtion)

['0' '0.5' '1.62' ... '2.54' '0' '5.15']


In [22]:
contry_canada = word_alcohol[:,2]=='Canada'

In [23]:
print(contry_canada)

[False False False ... False False False]


In [26]:
year_1984 = word_alcohol[:,0] == '1984'
print(year_1984)

[False False False ... False False False]


In [30]:
country_is_algeria =  word_alcohol[:,2]=="Algeria"
contry_algeria = word_alcohol[country_is_algeria]

In [31]:
contry_algeria

array([['1984', 'Africa', 'Algeria', 'Spirits', '0.01'],
       ['1987', 'Africa', 'Algeria', 'Beer', '0.17'],
       ['1987', 'Africa', 'Algeria', 'Spirits', '0.01'],
       ['1986', 'Africa', 'Algeria', 'Wine', '0.1'],
       ['1984', 'Africa', 'Algeria', 'Other', '0'],
       ['1989', 'Africa', 'Algeria', 'Beer', '0.16'],
       ['1989', 'Africa', 'Algeria', 'Spirits', '0.01'],
       ['1989', 'Africa', 'Algeria', 'Wine', '0.23'],
       ['1986', 'Africa', 'Algeria', 'Spirits', '0.01'],
       ['1984', 'Africa', 'Algeria', 'Wine', '0.12'],
       ['1985', 'Africa', 'Algeria', 'Beer', '0.19'],
       ['1985', 'Africa', 'Algeria', 'Other', '0'],
       ['1986', 'Africa', 'Algeria', 'Beer', '0.18'],
       ['1985', 'Africa', 'Algeria', 'Wine', '0.11'],
       ['1986', 'Africa', 'Algeria', 'Other', '0'],
       ['1989', 'Africa', 'Algeria', 'Other', '0'],
       ['1987', 'Africa', 'Algeria', 'Other', '0'],
       ['1984', 'Africa', 'Algeria', 'Beer', '0.2'],
       ['1985', 'Africa', 'A

In [32]:
contry_Algeria_1986 = (word_alcohol[:,2]=="Algeria" ) & (word_alcohol[:,0]=="1986")
contry_Algeria_1986

array([False, False, False, ..., False, False, False])

In [33]:
word_alcohol[contry_Algeria_1986]

array([['1986', 'Africa', 'Algeria', 'Wine', '0.1'],
       ['1986', 'Africa', 'Algeria', 'Spirits', '0.01'],
       ['1986', 'Africa', 'Algeria', 'Beer', '0.18'],
       ['1986', 'Africa', 'Algeria', 'Other', '0']], dtype='<U75')

In [55]:
word_alcohol[word_alcohol[:,0]=="1986",0] = "2018"

In [58]:
word_alcohol[word_alcohol[:,3] == "Wine",3] = "Biere"

In [59]:
word_alcohol

array([['2018', 'Western Pacific', 'Viet Nam', 'Biere', '0'],
       ['2018', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Biere', '1.62'],
       ...,
       ['2018', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['2018', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

In [76]:
is_empty = word_alcohol[:,4]==''
word_alcohol[is_empty,4] = '0'

In [77]:
word_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

In [85]:
alcol_consomtion = word_alcohol[:,4]
alcol_consomtion = alcol_consomtion.astype(float)

In [88]:
total_consomtion = alcol_consomtion.sum()
average_consomtion = alcol_consomtion.mean()

In [89]:
print(total_consomtion)

3908.96


In [90]:
print(average_consomtion)

1.2001719373656738


In [96]:
canada_1986 = (word_alcohol[:,0] == '1986') & (word_alcohol[:,2]=="Canada" )
canada_consomtion = word_alcohol[canada_1986,4].astype(float)
total_consomtion_canada = canada_consomtion.sum()

In [98]:
print(total_consomtion_canada)

9.31


In [116]:
#consommation total par pay
total_alcol = {}
is_1989 = word_alcohol[:,0]=="1986"
for pay in word_alcohol[is_1989,2]:
    consom_pay = word_alcohol[:,2] == pay
    total_alcol[pay] = word_alcohol[consom_pay,4].astype(float).sum()

print(total_alcol)
        

{'Viet Nam': 0.8300000000000002, 'Uruguay': 37.22, 'Colombia': 32.900000000000006, 'Antigua and Barbuda': 20.91, 'Myanmar': 1.3000000000000003, 'Italy': 62.29, 'Sierra Leone': 22.88, 'Micronesia (Federated States of)': 0.0, 'Russian Federation': 31.82, 'Sweden': 35.47, 'Czech Republic': 67.75, 'Mexico': 23.06, 'Malta': 27.43, 'Saudi Arabia': 1.23, 'Togo': 13.13, 'Madagascar': 6.570000000000001, 'Pakistan': 0.09999999999999999, 'Bolivia (Plurinational State of)': 15.8, 'Ukraine': 27.419999999999998, 'Sri Lanka': 1.05, 'Bahamas': 69.83999999999999, 'Lebanon': 19.060000000000002, 'Eritrea': 2.0700000000000003, 'Spain': 71.02000000000001, 'Gambia': 8.72, 'Nicaragua': 15.879999999999999, 'Belgium': 63.89, 'Zambia': 15.499999999999998, 'Uganda': 37.64000000000001, 'Cabo Verde': 14.19, 'Saint Kitts and Nevis': 19.290000000000003, 'Norway': 25.93, 'Australia': 62.480000000000004, 'Venezuela (Bolivarian Republic of)': 42.300000000000004, 'Cyprus': 42.019999999999996, 'Vanuatu': 9.29000000000000

In [118]:
#pay qui consomme plus d'alcol
contry = ''
consommation = 0
for t in total_alcol:
    if( total_alcol[t] > consommation):
        consommation = total_alcol[t]
        contry = t
print ('Pays: ',contry)
print('consommation: ',consommation)

Pays:  Hungary
consommation:  82.22
